[project]
name = "pyright-ot-benchmark"
version = "0.1.0"
description = "Benchmarking pyright's ability to type-check occurrence typing"
requires-python = "==3.12.6"

[tool.pyright]
include = ["*.py"]
venvPath = "."
venv = ".venv"
reportUnusedImport = false
