[project]
name = "ot-benchmark-mypy"
version = "0.1.0"
description = "Benchmarking mypy's ability to type-check occurrence typing"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.13.0",
]

[tool.mypy]
warn_unreachable = true
